package com.alexander.examples.cxf.spring.service.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Mon Jul 30 21:42:00 BST 2012
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://interfaces.service.spring.cxf.examples.alexander.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://interfaces.service.spring.cxf.examples.alexander.com/", className = "com.alexander.examples.cxf.spring.service.interfaces.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://interfaces.service.spring.cxf.examples.alexander.com/", className = "com.alexander.examples.cxf.spring.service.interfaces.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
